site_name: "NFT para Artistas"
repo_url: https://github.com/fransimo/nft_para_artistas
edit_uri: edit/main/docs/
extra:
  version: 1.0.0
  social:
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/fransimo
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/fransimo_nft
    - icon: fontawesome/brands/github
      link: https://github.com/fransimo/
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/fransimoart
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/in/fransimo
    - icon: fontawesome/solid/paper-plane
      link: mailto:contact@fransimo.info
    - icon: fontawesome/brands/mailchimp
      link: https://fransimo.us10.list-manage.com/subscribe?u=4e708ed8e3a29fc5dc139a011&id=7546e4b3aa

copyright: Apache License - 2022 - Fran Simó

plugins:
  - git-revision-date
  - print-site:
      add_to_navigation: false
      print_page_title: 'Print Site'
      add_print_site_banner: true
      # Table of contents
      add_table_of_contents: true
      toc_title: 'Table of Contents'
      toc_depth: 6
      # Content-related
      add_full_urls: false
      enumerate_headings: true
      enumerate_figures: true
      add_cover_page: true
      cover_page_template: ""
      path_to_pdf: ""
      include_css: true
      enabled: true
      exclude:

markdown_extensions:
  - admonition
  - pymdownx.details
  - pymdownx.superfences
  - tables
  - attr_list
  - md_in_html
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg

nav:
  # - 'Conexión': 'stream.md'
  # - '¡Hola mundo!': 'hello_world.md'
  - 'S01E01 - Introducción':
    - '¿Qué es un NFT?': '01_introduction/nft.md'
    - 'Plataformas y proyectos': '01_introduction/markets.md'
    - '¿Qué es un blockchain?': '01_introduction/blockchain.md'
    - 'Cómo crear un monedero Metamask': '01_introduction/metamask.md'
    - 'Comprar o vender NFT se hace con criptomonedas': '01_introduction/buy_sell.md'
    - 'Cómo crear una cuenta en OpenSea': '01_introduction/opensea.md'
    - 'Cómo crear una colección': '01_introduction/collection.md'
    - 'Colección: Conceptos NFT para Artistas': 'NFTs/index.md'
    - 'Publicación de NFTs, opciones de venta, subasta, etc.': '01_introduction/publish.md'
    - 'Comprar NFTs': '01_introduction/buy_sell_nft.md'
    - 'Show me the money!': '01_introduction/show_me_the_money.md'
    - 'Cómo hacer colecciones colaborativas': '01_introduction/collab.md'
    - 'Ciber seguridad': '01_introduction/cyber_security.md'
  - 'S01E02 - Ética y política': '02_ethics/index.md'
  - 'S01E03 - Estética': '03_aesthetics/index.md'
  - 'S01E04 - Mercado': '04_market/index.md'
  - 'Recursos': 'resources.md'
  - 'Donaciones': 'donate.md'
  - 'A cerca de':
      - 'Fran Simó': 'about/fran_simo.md'
      - 'Casa Planas': 'about/casa_planas.md'
      - 'Virtual Gallery Palma': 'about/virtual_gallery_palma.md'
      - 'License': 'license.md'
      - 'Release Notes': 'release-notes.md'
  - 'Imprimir': '/print_page/'

extra_css:
  - stylesheets/extra.css

theme:
  # name: mkdocs
  # name: bootstrap386
  # name: readthedocs
  # name: ivory
  # name: gitbook
  logo: assets/logo.png
  language: es
  name: material

  features:
    - navigation.tabs
    - navigation.tabs.sticky
    - navigation.sections
    - toc.integrate
  palette:
    - scheme: default
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to dark mode
    - scheme: slate
      primary: grey
      toggle:
        icon: material/lightbulb-outline
        name: Switch to light mode


  locale: es
  navigation_depth: 10
  prev_next_buttons_location: both
  collapse_navigation: False